<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSOE-CND52919J1" name="calculator.CalculatorTest" tests="11" failures="0" timestamp="6 Jan 2016 03:58:24 GMT" time="0.010" errors="1">
  <testcase name="testStandardOperations" time="0.000" classname="calculator.CalculatorTest"/>
  <testcase name="testNonIntegerSubstitution" time="0.001" classname="calculator.CalculatorTest"/>
  <testcase name="testBadCommand" time="0.003" classname="calculator.CalculatorTest"/>
  <testcase name="testStandardOperations" time="0.001" classname="calculator.CalculatorTest"/>
  <testcase name="testStandardOperations" time="0.000" classname="calculator.CalculatorTest"/>
  <testcase name="testExit" time="0.000" classname="calculator.CalculatorTest"/>
  <testcase name="testSubstitutionOperations" time="0.001" classname="calculator.CalculatorTest"/>
  <testcase name="testStandardOperations" time="0.001" classname="calculator.CalculatorTest"/>
  <testcase name="testStandardOperations" time="0.000" classname="calculator.CalculatorTest"/>
  <testcase name="testStandardOperations" time="0.001" classname="calculator.CalculatorTest">
    <error type="java.lang.AssertionError" message="expected:&lt;ADD [1.0, 2.0, 3.0] Answer: 6.0
SUB [3.0, 2.0, 1.0] Answer: 0.0
MULT [3.0, 2.0, 2.0] Answer: 12.0
DIV [6.0, 2.0, 3.0] Answer: 1.0
SQR [4.0] Answer: 16.0&gt; but was:&lt;SUB [2.0] Answer: 2.0
ADD [1.0, 2.0] Answer: 3.0
SUB [2.0] Answer: 2.0
ADD [1.0, 2.0, 3.0] Answer: 6.0
SUB [3.0, 2.0, 1.0] Answer: 0.0
MULT [3.0, 2.0, 2.0] Answer: 12.0
DIV [6.0, 2.0, 3.0] Answer: 1.0
SQR [4.0] Answer: 16.0&gt;">
      <![CDATA[java.lang.AssertionError: expected:<ADD [1.0, 2.0, 3.0] Answer: 6.0
SUB [3.0, 2.0, 1.0] Answer: 0.0
MULT [3.0, 2.0, 2.0] Answer: 12.0
DIV [6.0, 2.0, 3.0] Answer: 1.0
SQR [4.0] Answer: 16.0> but was:<SUB [2.0] Answer: 2.0
ADD [1.0, 2.0] Answer: 3.0
SUB [2.0] Answer: 2.0
ADD [1.0, 2.0, 3.0] Answer: 6.0
SUB [3.0, 2.0, 1.0] Answer: 0.0
MULT [3.0, 2.0, 2.0] Answer: 12.0
DIV [6.0, 2.0, 3.0] Answer: 1.0
SQR [4.0] Answer: 16.0>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at calculator.CalculatorTest.testStandardOperations(CalculatorTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </error>
  </testcase>
  <testcase name="testNonInteger" time="0.002" classname="calculator.CalculatorTest"/>
</testsuite>
